# https://github.com/elastic/logstash-docker
FROM logstash:5.5.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json


RUN logstash-plugin install x-pack
